### ISSUE TITLE
🙏 Request for Help: About OpenAI API Key

### ISSUE THREAD

**Issue by lencx** [lencx/nofwl#13]
Request for Help: I am unable to bind my card and recharge for ChatGPT due to my location. If anyone is kind enough to contribute an API Key, please send me a private message. I don't have a large usage volume and mainly use it for testing when developing applications. If you feel that the API Key is causing any abnormal calls or want to revoke my usage, you can delete it at any time.

Alternatively, if you know of a stable recharge method, please let me know so I can recharge myself (I am in China and cannot obtain an overseas bank card).

Email: cxin1314@gmail.com

**Comment by germanrauhut** [comment]
Sent you an Email

**Comment by DjSens** [comment]
to got API-key — install «Hotspot Shield VPN» or other,  reg at openAI using google account,   SMS you can got using service like [grizzlysms.com](https://grizzlysms.com/profile)  -there are you must select «for OpenAI»

**Comment by xiefeihong** [comment]
Sent you an Email

**Comment by GitHdu** [comment]
> Sent you an Email

myfly2013@111.com

can u send me a api key. 3q

**Comment by Captpricelsy** [comment]
Use Depay (virtual card), they accept USDT charging, though it may cost you some transaction fees. 1 dollar is approximately 7.6 rmb if you buy USDT at Huobi.

**Comment by Yahalqahtani** [comment]
> Use Depay (virtual card), they accept USDT charging, though it may cost you some transaction fees. 1 dollar is approximately 7.4 rmb if you buy USDT at Huobi (1 to 7.1 for small purchases) and then charge them into virtual cards.

hi , i need trust sites for virtual cards please

**Comment by L134139** [comment]
> 给您发送了一封电子邮件

Is there any stable gpt api recharge method
