### ISSUE TITLE
NoFWL_0.1.0_linux_x86_64.AppImage.tar.gz

### ISSUE THREAD

**Issue by ahnz7** [lencx/nofwl#15]
想请问一下，这个解压后怎么打不开？

**Comment by ahnz7** [comment]
顺便问一句，有支付宝/微信版的“buy me a coffee”吗？实在是不太方便

**Comment by lencx** [comment]
这里有写 https://github.com/lencx/nofwl#macos-macos_xxx-seems-broken
你安装成功后，可以点击菜单，里面可以赞助。

<img width="948" alt="Screenshot 2023-04-01 at 17 21 33" src="https://user-images.githubusercontent.com/16164244/229277642-6e15e8eb-6cff-492c-9aae-fc66078b4739.png">

**Comment by ahnz7** [comment]
> 这里有写 https://github.com/lencx/nofwl#macos-macos_xxx-seems-broken 你安装成功后，可以点击菜单，里面可以赞助。
> 
> <img alt="Screenshot 2023-04-01 at 17 21 33" width="948" src="https://user-images.githubusercontent.com/16164244/229277642-6e15e8eb-6cff-492c-9aae-fc66078b4739.png">

哦哦，好的，我没看到，已经支持了，辛苦了

**Comment by lencx** [comment]
感谢支持
