### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by nahid6970** [lencx/nofwl#17]
not working anymore when using any input this error shows "Request failed with status code 429"

**Comment by lencx** [comment]
[Error Code 429 - Rate limit reached for requests](https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests)

**Comment by chenzuoxian** [comment]
> 

官网显示API还正常，只有我一人使用，请问为什么也出现这种情况？

**Comment by nahid6970** [comment]
> [Error Code 429 - Rate limit reached for requests](https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests)

is there any solution?

**Comment by milesskorpen** [comment]
I'm getting this same error with every request starting yesterday, across multiple API keys. 
Open AI reports that the API key hasn't been used.

**Comment by nxtester** [comment]
Same here, "Status Code 429".

**Comment by tersapp** [comment]
got this error, any solution?

**Comment by LurieWong** [comment]
同样的key，在Windows版本正常使用，在Intel Mac上使用提示429，换key也不行

**Comment by Culacco** [comment]
guys, I know. check your api account and set up payment card. The reason is that api cost and the trail $18 has expired

**Comment by Letlaka** [comment]
> guys, I know. check your api account and set up payment card. The reason is that api cost and the trail $18 has expired

Thanks this resolved my issue.
