### ISSUE TITLE
Will this project support working with my own ChatGpt API Key?

### ISSUE THREAD

**Issue by MoonNarga** [lencx/nofwl#2]
Just as the title said, I used to try "ChatGPT", but it didn't solve that I need to refresh it frequently. And I already get the API key, it would be good to use it instead of log in with openai account

**Comment by lencx** [comment]
download: https://github.com/lencx/nofwl/releases

**Comment by ysun** [comment]
:+1: 

> download: https://github.com/lencx/nofwl/releases

**Comment by MoonNarga** [comment]
> download: https://github.com/lencx/nofwl/releases

Really nice experience! Look forward to more functions and hope to develop with you
